variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -X  # Füge den Debug-Parameter hinzu

image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository

stages:
  - build
  - verify
  - deploy

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'

verify:
  stage: verify
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'

deploy:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy'
  only:
    - main
    - /^feature\/.*$/
