# Using Maven with OpenJDK 8 for the CI/CD pipeline
image: maven:3-openjdk-8

# Cache Maven dependencies between builds
cache:
  paths:
    - .m2/repository

# Define global variables and options for Maven commands
variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

stages:
  - verify
  - deploy

# Test stage - Verify the build
verify:
  stage: verify
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'

# Deploy stage - Deploy to GitLab Maven repository on main branch
deploy:
  stage: deploy
  script:
    - if [ ! -f ci_settings.xml ]; then
      echo "CI settings missing! Please create ci_settings.xml following GitLab’s Maven Repository guide.";
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml'
  only:
    - main
