variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -X  # Füge den Debug-Parameter hinzu

image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository

stages:
  - build
  - verify
  - deploy

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'

verify:
  stage: verify
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'

deploy:
  stage: deploy
  script:
    - |
      if [ ! -f ci_settings.xml ]; then
        echo "CI settings file missing! Please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions."
        exit 1
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml -DskipTests'
  only:
    - main
    - /^feature\/.*$/

pages:
  image: node:8.12.0
  cache:
    paths:
      - frontend/node_modules/
  stage: deploy
  script:
    - cd frontend
    - npm install -g @angular/cli@6.2.1
    - npm install
    - ng build
    - mkdir -p public
    - mv dist/frontend/* public/
  artifacts:
    paths:
      - frontend/public
  only:
    - master
    - pages
