# Spring Boot application name
spring.application.name=Localy

# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/localydb
spring.datasource.username=localyuser
spring.datasource.password=localysecret
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.auth0.client-id=Zu6wgsXICHZ98RiOsJfTqN5JUDLrXsop
spring.security.oauth2.client.registration.auth0.client-secret=2i6divCpDTdJveeNCdOBLxCgSo0td0qc1SLqrpgYMUTN936XjrJXRX1eqB8u6inT
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.client-name=Auth0

# OAuth2 Provider Configuration
spring.security.oauth2.client.provider.auth0.issuer-uri=dev-7kd3aodtgm2bxgsl.eu.auth0.com

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=dev-7kd3aodtgm2bxgsl.eu.auth0.com