version: '3.8'

services:
  # PostgreSQL für Localy
  localy_postgres:
    image: postgres:15-alpine
    container_name: localy_postgres
    restart: always
    env_file:
      - ./env/postgres_localy.env
    volumes:
      - localy_pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # PostgreSQL für Auth
  auth_postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    restart: always
    env_file:
      - ./env/postgres_auth.env
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  # MQTT-Broker
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    restart: always
    ports:
      - '1883:1883'

  # Spring Boot Service für Localy
  localy_service:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    container_name: localy_service
    restart: on-failure
    depends_on:
      - localy_postgres
      - auth_postgres
      - mqtt_broker
    ports:
      - '8080:8080'
    env_file:
      - ./env/localy_service.env

  # Spring Boot Service für Authentication
  authentication_service:
    build:
      context: ../../Authentication
      dockerfile: docker/backend.Dockerfile
    container_name: authentication_service
    restart: on-failure
    depends_on:
      - auth_postgres
      - mqtt_broker
    ports:
      - '8090:8090'
    env_file:
      - ./env/auth_service.env

volumes:
  localy_pgdata:
  auth_pgdata:
